package de.se.tinf11b3.breakdown.gui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.VerticalLayout;

public class Schwierigkeitsgrad extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;

	@AutoGenerated
	private VerticalLayout verticalLayout_1;

	@AutoGenerated
	private Button button_schwer;

	@AutoGenerated
	private Button button_mittel;

	@AutoGenerated
	private Button button_leicht;

	private Spielfenster spielfenster = new Spielfenster();
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Schwierigkeitsgrad() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		button_leicht.addStyleName("button-leicht");
		button_mittel.addStyleName("button-mittel");
		button_schwer.addStyleName("button-schwer");
		
		button_leicht.addListener(new ClickListener(
				) {
			
			public void buttonClick(ClickEvent event) {
				getWindow().setContent(spielfenster);
			}
		});
		
		
		button_mittel.addListener(new ClickListener() {
			
			public void buttonClick(ClickEvent event) {
				getWindow().setContent(spielfenster);
			}
		});
		
		
		button_schwer.addListener(new ClickListener() {
			
			public void buttonClick(ClickEvent event) {
				getWindow().setContent(spielfenster);
			}
		});
		
		
		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		mainLayout.addComponent(verticalLayout_1, "top:20.0%;left:20.0%;");
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("240px");
		verticalLayout_1.setHeight("140px");
		verticalLayout_1.setMargin(false);
		
		// button_leicht
		button_leicht = new Button();
		button_leicht.setCaption("Leicht");
		button_leicht.setImmediate(true);
		button_leicht.setWidth("100.0%");
		button_leicht.setHeight("-1px");
		verticalLayout_1.addComponent(button_leicht);
		
		// button_mittel
		button_mittel = new Button();
		button_mittel.setCaption("Mittel");
		button_mittel.setImmediate(true);
		button_mittel.setWidth("100.0%");
		button_mittel.setHeight("-1px");
		verticalLayout_1.addComponent(button_mittel);
		
		// button_schwer
		button_schwer = new Button();
		button_schwer.setCaption("Schwer");
		button_schwer.setImmediate(true);
		button_schwer.setWidth("100.0%");
		button_schwer.setHeight("-1px");
		verticalLayout_1.addComponent(button_schwer);
		
		return verticalLayout_1;
	}

}
